apiVersion: v1
kind: Namespace
metadata:
  annotations:
    jenkins-x.io/created-by: Jenkins X
  labels:
    env: staging
    certmanager.k8s.io/disable-validation: true
  name: jx-staging
spec:
  finalizers:
  - kubernetes
